//
// Created by Adnane Azaoum on 20/04/2022.
//

#ifndef DEV4_STRATEGO_PHA_05_LOGMESSAGE_H
#define DEV4_STRATEGO_PHA_05_LOGMESSAGE_H

#include <string>
/**
 * Describe all errors and value to return
 */

enum LogMessage {
    NO_ERROR,
    ERROR,
    PIECE_NOT_FOUND,
    TEMPLATE_RED_NOT_FOUND,
    TEMPLATE_MANUAL_RED_NOT_FOUND,
    TEMPLATE_BLUE_NOT_FOUND,
    TEMPLATE_MANUAL_BLUE_NOT_FOUND,
    ERROR_IN_TEMPLATE,
    WANT_LOAD_TEMPLATE,
    DONT_WANT_LOAD_TEMPLATE,
    PIECE_CANT_MOVE,
    PIECE_ATTACK_ALLY,
    PIECE_WANT_MOVE_AT_FROM_POS,
    PIECE_NOT_FOUND_AT_FROM_POS,
    DIDNT_MADE_A_CHOICE
};


#endif //DEV4_STRATEGO_PHA_05_ERRORENUM_H
